Fixed code incompatibility with SleekXMPP==1.3.2 (#70)
* issue #69 TypeError: 'unicode' object does not support item assignment

[Stanzas: Message wiki page](https://github.com/fritzy/SleekXMPP/wiki/Stanzas:-Message) says that msg['html']['body']` was never part of it and a [XEP-0071](https://xmpp.org/extensions/xep-0071.html) needs to be loaded in order to work.

* issue #69 AttributeError: 'unicode' object has no attribute 'bare'

Error was caused because SleekXMPP in version 1.3.1 returned JID object,
but in version 1.3.2 returned string. I have created function so the fix
is compatible if someone update just Ludolph without SleekXMPP.

* issue #69 Updated version to use SleekXMPP version

* fixed changes requested in code review in PR #70

* Explained why we are introducing new function in order to be able to monitor it

* Shortened link so we do not exceed line length

* closes issue #69